"""create book add table

Revision ID: c12e4db3861f
Revises: 
Create Date: 2023-12-15 22:43:37.210465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c12e4db3861f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('genre', sa.Text(), nullable=False),
    sa.Column('sub_genre', sa.Text(), nullable=False),
    sa.Column('publication_year', sa.Integer(), nullable=False),
    sa.Column('ISBN', sa.Integer(), nullable=False),
    sa.Column('copies_available', sa.Integer(), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=False),
    sa.Column('cover_image', sa.VARCHAR(), nullable=False),
    sa.Column('created__at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
